# Generated by Django 5.2.3 on 2025-06-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_user_phone_alter_user_profile_picture'),
    ]

    operations = [
    ]
