# Generated by Django 5.2.3 on 2025-06-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20250614_0959'),
    ]

    operations = [
    ]
