# Generated by Django 5.2.3 on 2025-06-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
