# Generated by Django 5.2.3 on 2025-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='entry',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_public',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
