# Generated by Django 5.2.3 on 2025-06-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_collection_created_at_collection_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
