# Generated by Django 5.2.3 on 2025-06-18 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_mood_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moods', to=settings.AUTH_USER_MODEL),
        ),
    ]
