# Generated by Django 5.2.3 on 2025-06-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_mood_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mood',
            name='emoji',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
